name: GameMode
version: '${project.version}'
main: cn.paper_card.gamemode.GameMode
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  gamemode:
    permission: paper-card.gamemode.command

permissions:
  paper-card.gamemode.command:
    default: op
